// English for the demo data in mock.ts (dev only). Real content is written by projects and testers;
// for campaigns, projects can enter an English copy in the create form.
export const sampleEn: Record<string, string> = {
  'Test luồng đăng nhập và trả lời đa ngôn ngữ': 'Test sign-in and multilingual answers',
  'Chatbot AI chăm sóc khách hàng cho sàn thương mại điện tử.': 'An AI customer-support chatbot for an e-commerce marketplace.',
  'Đăng nhập bằng email và Google\nTrả lời bằng tiếng Việt, Anh, Nhật\nLịch sử hội thoại và xuất file': 'Sign in with email and Google\nAnswers in Vietnamese, English and Japanese\nChat history and file export',
  'Lỗi chính tả trong giao diện\nTấn công DDoS, spam tài khoản': 'Typos in the interface\nDDoS attacks, account spam',
  'Tìm lỗi chuyển giọng nói tiếng Việt': 'Find bugs in Vietnamese speech-to-text',
  'Ứng dụng ghi chú bằng giọng nói.': 'A voice note-taking app.',
  'Nhận dạng giọng ba miền\nTóm tắt ghi chú': 'Recognition of Northern, Central and Southern accents\nNote summaries',
  'Kiểm thử API sinh ảnh': 'Test the image generation API',
  'API sinh ảnh từ prompt.': 'An API that generates images from prompts.',
  'Endpoint /generate và /upscale': 'The /generate and /upscale endpoints',
  'Test ứng dụng mobile PromptForge': 'Test the PromptForge mobile app',
  'Ứng dụng iOS/Android sinh ảnh.': 'An iOS/Android image generation app.',
  'Luồng tạo ảnh, lưu, chia sẻ': 'Create, save and share flows',
  '1. Mở sản phẩm\n2. Làm theo luồng chính\n3. Quan sát kết quả': '1. Open the product\n2. Follow the main flow\n3. Watch the result',
  'Hoạt động đúng': 'Works correctly',
  'Có lỗi': 'Something breaks',
  'Trả lời tiếng Nhật bị cắt sau 200 ký tự': 'Japanese answers are cut off after 200 characters',
  '1. Đăng nhập bằng Google\n2. Chọn ngôn ngữ Nhật\n3. Hỏi một câu dài hơn 3 đoạn': '1. Sign in with Google\n2. Choose Japanese\n3. Ask a question longer than 3 paragraphs',
  'Câu trả lời đầy đủ': 'The full answer',
  'Bị cắt, không có nút xem tiếp': 'Cut off, with no "show more" button',
  'Mất lịch sử hội thoại sau khi đăng xuất': 'Chat history disappears after signing out',
  'Đã có người báo lỗi này từ hôm qua.': 'Someone reported this yesterday.',
  'Nhận sai từ "nhà" thành "nhả" với giọng miền Trung': 'Misrecognizes "nhà" as "nhả" with a Central accent',
  'Giọng miền Trung chưa nằm trong cam kết.': 'Central accents are not covered yet.',
  'Phạm vi test ghi rõ "Nhận dạng giọng ba miền", miền Trung nằm trong phạm vi.': 'The scope says "recognition of all three regional accents", so Central is in scope.',
  'Tóm tắt bỏ sót số điện thoại trong ghi chú': 'Summaries drop phone numbers from notes',
  'Tóm tắt nằm trong phạm vi test.': 'Summaries are in scope.',
  'Phạm vi có ghi "Tóm tắt ghi chú". Tester đúng.': 'The scope lists "note summaries". The tester is right.',
  'Nút xuất PDF không phản hồi trên Safari': 'The PDF export button does nothing on Safari',
  'Chatbot trả lời bằng tiếng Anh khi hỏi bằng tiếng Việt không dấu': 'The chatbot answers in English to Vietnamese typed without accents',
  'Tiếng Việt không dấu chưa hỗ trợ.': 'Vietnamese without accents is not supported yet.',
  'Phạm vi ghi "Trả lời bằng tiếng Việt", không loại trừ tiếng Việt không dấu.': 'The scope says "answers in Vietnamese" and does not exclude unaccented Vietnamese.',
  '/upscale trả 500 khi ảnh đầu vào là PNG trong suốt': '/upscale returns 500 for transparent PNG input',
  '1. Gọi /generate với prompt bất kỳ\n2. Gửi ảnh PNG có kênh alpha tới /upscale': '1. Call /generate with any prompt\n2. Send a PNG with an alpha channel to /upscale',
  'Ảnh được phóng to': 'The image is upscaled',
  'HTTP 500, body rỗng': 'HTTP 500 with an empty body',
  'Prompt tiếng Việt có dấu bị lỗi mã hoá trong metadata': 'Accented Vietnamese prompts are garbled in metadata',
  '1. Gọi /generate với prompt "phố cổ Hội An"\n2. Xem trường prompt trong response': '1. Call /generate with the prompt "phố cổ Hội An"\n2. Check the prompt field in the response',
  'Giữ nguyên dấu': 'Accents are preserved',
  'Hiện "ph? c? H?i An"': 'Shows "ph? c? H?i An"',
  'Giới hạn rate limit không trả header Retry-After': 'Rate limiting does not return a Retry-After header',
  'Ảnh 4K bị crop mất viền phải': '4K images lose their right edge when cropped',
  'QA 3 năm, chuyên test API.': '3 years in QA, focused on API testing.',
  'Mình từng test API của nhiều dịch vụ sinh ảnh.': "I've tested the APIs of several image generation services.",
  'Báo cáo rất rõ, có video kèm theo.': 'Very clear report with a video.',
  'Tìm ra lỗi bảo mật nghiêm trọng, mô tả chi tiết từng bước.': 'Found a serious security bug and documented every step.',
  'Phản hồi nhanh khi được hỏi thêm.': 'Replied quickly when asked for more info.',
  'Một số báo cáo thiếu bước tái hiện.': 'Some reports were missing reproduction steps.',
  'Test API rất kỹ, gửi kèm script tái hiện.': 'Very thorough API testing, with a reproduction script.',
  'Kiểm thử tóm tắt hợp đồng PDF': 'Test PDF contract summaries',
  'Tìm lỗi phụ đề tự động cho video ngắn': 'Find bugs in auto-captions for short videos',
  'Test API dịch thuật đa ngôn ngữ': 'Test a multilingual translation API',
  'Kiểm tra gia sư AI trả lời bài tập toán': 'Check an AI tutor answering math homework',
  'Test trợ lý mua sắm gợi ý sản phẩm': 'Test a shopping assistant that recommends products',
  'Săn lỗi plugin sinh code cho VS Code': 'Hunt bugs in a VS Code code-generation plugin',
  'Không tìm thấy (dữ liệu mẫu).': 'Not found (demo data).',
}
